# Site settings
title: xautjzd
email: xautjzd@gmail.com  
description: > # this means to ignore newlines until "baseurl:"
    博学之,审问之,慎思之,明辨之,笃行之
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:year/:month/:day/:title.html
url: "http://xautjzd.github.io" # the base hostname & protocol for your site
twitter_username: xautjzd
github_username: xautjzd

# Build settings
markdown: kramdown
highlighter: pygments
